### PR TITLE
Correct mistakes in BSD license headers

### PR DESCRIPTION
**Pull request by pabs3**
comment_handler.py had "this " replaced with "self." and
tokenizer.py had two missing colons after SERVICES/PROFITS.

Fixes: commit cc445ea30e332ea09632eccf80de0b930e2e3ef4

### CODE REVIEW

**Comment by Kronuz** [comment]
Thank you for noticing and fixing these!

**Comment by pabs3** [comment]
No problem. I was reviewing the code while packaging it for Debian,
since it is a new dependency of librecaptcha, which I was updating.

BTW, I note that 16 of the tests are failing with Python 3.9 and only 8
of them are failing with Python 3.5 but only one is expected to fail.
Has there be a regression due to changes in Python?

Also test/3rdparty/ doesn't seem to be used by the test suite?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by Kronuz** [comment]
I haven't been maintaining the package for some time... so I don't know why things are broken in 3.9 😕

About that other 3rdparty directory, I don't remember. I probably just put it there because it was in the original esprima, but maybe it's missing to add a runner for those tests

**Comment by pabs3** [comment]
OK, thanks for the info.

I note there is another translation of esprima to Python here,
unfortunately it is also not maintained.

https://github.com/PiotrDabkowski/pyjsparser

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Pull request merged**
